services:
  mysql-olist:
    image: mysql:8.0
    container_name: mysql_olist_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_olist
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - olist_mysql_data:/var/lib/mysql

volumes:
  olist_mysql_data: